azure {
  storageAccount = "dataraystg"
  container = "bronze"
  clientId = ""
  tenantId = ""
  clientSecret = ""
}

spark {
  app {
    name = "DataProcess"
    master = "local[*]"
  }
  
  sql {
    shuffle.partitions = 200
  }
}

environment = ${?ENVIRONMENT} 
