azure {
  storageAccount = "dataraystg"
  container = "bronze"
  clientId = "6fc3974d-be67-4a11-83a6-86745f9ea948"
  tenantId = "9b03c2ab-3ace-47a7-98de-0740ec542511"
  clientSecret = "wc28Q~3NUwD7Ol5rrx2OJKzdZ4O7hsxqfVbYCbiG"
}

spark {
  app {
    name = "DataProcess"
    master = "local[*]"
  }
  
  sql {
    shuffle.partitions = 200
  }
}

environment = ${?ENVIRONMENT} 